<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-10 at 17:28:21.
 */
require_once dirname(__FILE__) . '/../clsCaptcha.class.php';
class CaptchaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Captcha
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Captcha("2tvcdfn45wxhj38g67pqrskm9byz", "../fontesCaptcha", "../imagenCaptcha");;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Captcha::setPastaSouceCaptcha
     * @todo   Implement testSetPastaSouceCaptcha().
     */
    public function testSetPastaSouceCaptcha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Captcha::setPastaFontesTTF
     * @todo   Implement testSetPastaFontesTTF().
     */
    public function testSetPastaFontesTTF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Captcha::setListaCaracteres
     * @todo   Implement testSetListaCaracteres().
     */
    public function testSetListaCaracteres() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Captcha::captchaGerator
     * @todo   Implement testCaptchaGerator().
     */
    public function testCaptchaGerator() {
        // Remove the following lines when you implement this test.
       $this->assertEquals(
                2, 
               $this->object->captchaGerator(120, 40, 5)
        );
    }

    /**
     * @covers Captcha::randonSequence
     * @todo   Implement testRandonSequence().
     */
    public function testRandonSequence() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Captcha::getCodeCaptcha
     * @todo   Implement testGetCodeCaptcha().
     */
    public function testGetCodeCaptcha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Captcha::getCaminhoImagem
     * @todo   Implement testGetCaminhoImagem().
     */
    public function testGetCaminhoImagem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Captcha::codeChecker
     * @todo   Implement testCodeChecker().
     */
    public function testCodeChecker() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
